name: Package

on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run lint && npm run test
      - run: npm run pkg
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
